### ISSUE TITLE
Not working with react/http-client >= 0.4.13

### ISSUE THREAD

**Issue by joelwurtz** [php-http/react-adapter#17]
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Version |  |
#### Actual Behavior

This library return a error when creating an response
#### Expected Behavior

Working :)
#### Steps to Reproduce

Use last version of react/http-client
#### Possible Solutions

We should rework the way the response is build, it's no longer working since this PR has been merged into react/http-client https://github.com/reactphp/http-client/pull/66

**Comment by shulard** [comment]
I'll take a look today 😄.
