### ISSUE TITLE
Add support for HHVM in Travis

### ISSUE THREAD

**Issue by shulard** [php-http/react-adapter#2]
I've just authorized HHVM build to fail on travis because I can't check for the moment why the build fail. We need to make the whole build pass (and remove fail authorization from .travis-ci.yml).

**Comment by Nyholm** [comment]
Hey.  

There has not been a major request for this feature. Also, larger projects are dropping the support for hhvm. If you do not mind, I'll close this issue. Feel free to reopen it if you want.
