### ISSUE TITLE
Move forward and use react/http

### ISSUE THREAD

**Issue by shulard** [php-http/react-adapter#41]
**Description**

Hello, I see that the `react/http-client` library is now archived and is replaced with `react/http`. Do you plan to move to the new package ? Will it be considered as a breaking change (so maybe tied to #34) ?

**Additional context**

I juste started a new project where I want to use some specific react capabilities. I would like to use the httplug ecosystem (and maybe PSR-18) as a valid interface. I can work on the update if you need some help ^^

**Comment by dbu** [comment]
hi @shulard, looking at https://github.com/php-http/react-adapter/graphs/contributors i would consider you the main author of this adapter ;-)
i guess doing it as a new major version sounds like a good idea to not be hindered by BC considerations. i can imagine that some hidden unexpected side effects could otherwise happen. (well they can still happen, but with a new major that is less of a problem)

**Comment by dbu** [comment]
we could also take the opportunity to go to php 7.2 and do typed parameters and method returns wherever possible.

**Comment by shulard** [comment]
You are right but my last contribution was a long time ago ^^. So I'll work on a PR for the next major release and I'll add php 7.2 specific code with typed parameters and return values.

**Comment by shulard** [comment]
@dbu I think we are ready for the 3.0.0 release :smile:. I prepared a draft release in GitHub but I've one little question regarding code sniffing.

We were using StyleCI to check the code but it seems that the configuration were removed from the `php-http/message` package. Is it still useful to use this tool ?
The code sniffing is also validated using PHP_CS_Fixer were the code reach `master`…

**Comment by dbu** [comment]
i think the codestyle run in the actions is enough and we can remove the styleci. only upside is that you can make styleci do a pull request on a branch with the cs fixes, but one can run the cs fixer on the command line as well, imho that is good enough.

**Comment by shulard** [comment]
Ok, I haven't sufficient permissions to remove StyleCI (and it seems that the rules are not strictly the same than with cs fixer) but since we agreed on that point, I just created the 3.0.0.
