### ISSUE TITLE
Add puli bindings

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/react-adapter#7]

**Comment by shulard** [comment]
Hello,

Can you explain me how to do that ? Is there a repo with a valid binding ?

**Comment by sagikazarmark** [comment]
Sure.

https://github.com/php-http/guzzle6-adapter/blob/master/puli.json

Although copy pasting is not a good idea, as the id has to be unique. I suggest taking a look at the puli cli documentation:

http://docs.puli.io/en/latest/discovery/providing-resources.html

**Comment by shulard** [comment]
I think that it's ok, is there a way to validate that the puli.json is right ?

**Comment by sagikazarmark** [comment]
Dunno, doesn't the puli command provide a validate command? Since it is JSON, JsonSchema would be the obvious choice.

/cc @webmozart

**Comment by shulard** [comment]
The file is a valid JSON but I really don't understand where pulli can help here :smile: 

I would like to check that the file can be used in a real example... I generated it with the pulli cli so it must be fine...

**Comment by sagikazarmark** [comment]
I commented on the commit, you must add the FQCN instead of the path. But you are free to edit the file, no need to use puli update command.

JsonSchema does not validate JSON itself, but the data in it, so that it matches the required structure.

**Comment by shulard** [comment]
Ok thanks !

**Comment by sagikazarmark** [comment]
:+1:
